#pragma once

#define NOCLIPBOARD
//#define NOCOLOR
//#define NOCTLMGR
#define NODEFERWINDOWPOS
#define NODRAWTEXT
//#define NOGDI
#define NOGDICAPMASKS
#define NOHELP
#define NOICONS
#define NOIME
#define NOKEYSTATES
//#define NOMB
#define NOMCX
#define NOMENUS
#define NOMETAFILE
#define NOMINMAX
//#define NOMSG
//#define NONLS
#define NOOPENFILE
#define NOPROFILER
#define NORASTEROPS
#define NOSCROLL
#define NOSERVICE
//#define NOSHOWWINDOW
#define NOSYSCOMMANDS
#define NOSYSMETRICS
//#define NOTEXTMETRIC
//#define NOUSER
#define NOVIRTUALKEYCODES
#define NOWH
//#define NOWINMESSAGES
//#define NOWINOFFSETS
#define NOWINSTYLES
#define OEMRESOURCE
#define WIN32_LEAN_AND_MEAN
