name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.configuration }} ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'cpp'

      - name: Build
        shell: cmd
        run: build.bat ${{ matrix.configuration }} ${{ matrix.platform }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            ${{ matrix.platform }}/${{ matrix.configuration }}/*.ax
            ${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb
          retention-days: 7
          if-no-files-found: error
