name: CI

on: workflow_dispatch

jobs:
    build:
        name: ${{ matrix.config.platform }}
        runs-on: windows-latest
        strategy:
            matrix:
                config:
                    - { platform: 'x64' }
                    - { platform: 'x86' }
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v1
              with:
                  languages: 'cpp'

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1

            - name: Build
              shell: cmd
              run: |
                  set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE";%PATH%
                  build.bat ${{ matrix.config.platform }}

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v1
