name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.configuration }} ${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - configuration: Release
            platform: x64
            output-dir: x64
          - configuration: Release
            platform: x86
            output-dir: Win32
          - configuration: Debug
            platform: x64
            output-dir: x64
          - configuration: Debug
            platform: x86
            output-dir: Win32
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: cmd
        run: build.bat ${{ matrix.configuration }} ${{ matrix.platform }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.configuration }} ${{ matrix.platform }}
          path: |
            ${{ matrix.output-dir }}/${{ matrix.configuration }}/*.ax
            ${{ matrix.output-dir }}/${{ matrix.configuration }}/*.pdb
          if-no-files-found: error
