name: CI

on:
    workflow_dispatch

jobs:
    build:
        name: ${{ matrix.config.platform }}
        runs-on: windows-latest
        strategy:
            matrix:
                config:
                - {platform: "x64"}
                - {platform: "x86"}

        steps:
            - uses: actions/checkout@v2

            - name: setup-msbuild
              uses: microsoft/setup-msbuild@v1

            - name: build
              shell: cmd
              run: |
                  set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE";%PATH%
                  build.bat ${{ matrix.config.platform }}
